import 'dart:convert';
import 'dart:io';
import 'package:http/http.dart' as http;

class CloudinaryService {
  // Replace with your actual Cloudinary Cloud Name
  final String cloudName = 'dlk8chosr';
  final String uploadPreset = 'blood_connect_upload';

  Future<String> uploadImage(File imageFile) async {
    final uri = Uri.parse(
      'https://api.cloudinary.com/v1_1/$cloudName/image/upload',
    );

    final request = http.MultipartRequest('POST', uri)
      ..fields['upload_preset'] = uploadPreset
      ..files.add(await http.MultipartFile.fromPath('file', imageFile.path));

    final response = await request.send();

    if (response.statusCode == 200) {
      final responseData = await response.stream.toBytes();
      final jsonResponse = jsonDecode(String.fromCharCodes(responseData));
      // Returns the HTTPS URL generated by Cloudinary
      return jsonResponse['secure_url'] as String;
    } else {
      throw Exception(
        'Failed to upload image to Cloudinary (Status: ${response.statusCode})',
      );
    }
  }
}
