// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRnTb1OdDb6JHc_6vbSnaJn7iY3T928SI',
    appId: '1:394558242984:web:9ba9085bac8c24eb8c029d',
    messagingSenderId: '394558242984',
    projectId: 'blood-connect-12ac2',
    authDomain: 'blood-connect-12ac2.firebaseapp.com',
    storageBucket: 'blood-connect-12ac2.firebasestorage.app',
    measurementId: 'G-VQY4C80BYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-b8V1nIaUxQ5R5xKkstwzUzl-O-quN4',
    appId: '1:394558242984:android:c5b84458c7404eb98c029d',
    messagingSenderId: '394558242984',
    projectId: 'blood-connect-12ac2',
    storageBucket: 'blood-connect-12ac2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsYLV99VaQDkLVG2Up9xufP2t1LDf0ii4',
    appId: '1:394558242984:ios:08021bf451cc9f6b8c029d',
    messagingSenderId: '394558242984',
    projectId: 'blood-connect-12ac2',
    storageBucket: 'blood-connect-12ac2.firebasestorage.app',
    iosBundleId: 'com.example.bloodConnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsYLV99VaQDkLVG2Up9xufP2t1LDf0ii4',
    appId: '1:394558242984:ios:08021bf451cc9f6b8c029d',
    messagingSenderId: '394558242984',
    projectId: 'blood-connect-12ac2',
    storageBucket: 'blood-connect-12ac2.firebasestorage.app',
    iosBundleId: 'com.example.bloodConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRnTb1OdDb6JHc_6vbSnaJn7iY3T928SI',
    appId: '1:394558242984:web:f52fdddadae8b0408c029d',
    messagingSenderId: '394558242984',
    projectId: 'blood-connect-12ac2',
    authDomain: 'blood-connect-12ac2.firebaseapp.com',
    storageBucket: 'blood-connect-12ac2.firebasestorage.app',
    measurementId: 'G-1ZJ7WTESJ5',
  );
}
